USE [UtilitiesMasterPlan]
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE VIEW [dbo].[ViewHighVoltageBuildingCapacity]
AS

SELECT        dbo.HIGHVOLTAGEBUILDINGS.OBJECTID, dbo.HIGHVOLTAGEBUILDINGS.FeatureStatus, dbo.HIGHVOLTAGEBUILDINGS.FeatureStatusDate, dbo.HIGHVOLTAGEBUILDINGS.FieldStatus, 
                         dbo.HIGHVOLTAGEBUILDINGS.FieldStatusDate, dbo.HIGHVOLTAGEBUILDINGS.Notes, dbo.HIGHVOLTAGEBUILDINGS.FacNum, dbo.HIGHVOLTAGEBUILDINGS.FacCode, dbo.HIGHVOLTAGEBUILDINGS.FacName, 
                         dbo.HIGHVOLTAGEBUILDINGS.Site, dbo.HIGHVOLTAGEBUILDINGS.Address, dbo.HIGHVOLTAGEBUILDINGS.Ownership, dbo.HIGHVOLTAGEBUILDINGS.YearBuilt, dbo.HIGHVOLTAGEBUILDINGS.GSF, 
                         dbo.HIGHVOLTAGEBUILDINGS.BaseMap, dbo.HIGHVOLTAGEBUILDINGS.Underground, dbo.HIGHVOLTAGEBUILDINGS.RGUID, dbo.HIGHVOLTAGEBUILDINGS.GlobalID, dbo.HIGHVOLTAGEBUILDINGS.created_user, 
                         dbo.HIGHVOLTAGEBUILDINGS.created_date, dbo.HIGHVOLTAGEBUILDINGS.last_edited_user, dbo.HIGHVOLTAGEBUILDINGS.last_edited_date, dbo.HIGHVOLTAGEBUILDINGS.SHAPE, 
                         dbo.HIGHVOLTAGEBUILDINGS.GDB_GEOMATTR_DATA, dbo.HIGHVOLTAGEBUILDINGS.FeederZone, dbo.UNIVERSITYBUILDINGS.ZoneCapacity, dbo.UNIVERSITYBUILDINGS.PercentOfCapacity, 
                         dbo.UNIVERSITYBUILDINGS.Notes AS FeederZoneNotes
FROM            dbo.HIGHVOLTAGEBUILDINGS INNER JOIN
                         dbo.UNIVERSITYBUILDINGS ON dbo.HIGHVOLTAGEBUILDINGS.FeederZone = dbo.UNIVERSITYBUILDINGS.FeederZone
WHERE		(UtilitiesMasterPlan.dbo.HIGHVOLTAGEBUILDINGS.FeederZone IS NOT NULL)
	GO