USE [master]
GO

/****** Object:  Database [FacilitiesMaintenance]    Script Date: 10/12/2018 11:22:25 AM ******/
DROP DATABASE [FacilitiesMaintenance]
GO

/****** Object:  Database [FacilitiesMaintenance]    Script Date: 10/12/2018 11:22:25 AM ******/
CREATE DATABASE [FacilitiesMaintenance]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FacilitiesMaintenance', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FacilitiesMaintenance.mdf' , SIZE = 16061248KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FacilitiesMaintenance_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\FacilitiesMaintenance_log.ldf' , SIZE = 4005888KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [FacilitiesMaintenance] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FacilitiesMaintenance].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [FacilitiesMaintenance] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET ARITHABORT OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [FacilitiesMaintenance] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [FacilitiesMaintenance] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET  DISABLE_BROKER 
GO

ALTER DATABASE [FacilitiesMaintenance] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [FacilitiesMaintenance] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [FacilitiesMaintenance] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [FacilitiesMaintenance] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET RECOVERY FULL 
GO

ALTER DATABASE [FacilitiesMaintenance] SET  MULTI_USER 
GO

ALTER DATABASE [FacilitiesMaintenance] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [FacilitiesMaintenance] SET DB_CHAINING OFF 
GO

ALTER DATABASE [FacilitiesMaintenance] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [FacilitiesMaintenance] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [FacilitiesMaintenance] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [FacilitiesMaintenance] SET QUERY_STORE = OFF
GO

USE [FacilitiesMaintenance]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE [FacilitiesMaintenance] SET  READ_WRITE 
GO

